### ISSUE TITLE
Software Security Auditor

### ISSUE THREAD

**Issue by dnesterhp** [pythonph/jobs#17]
Company Name:  Hewlett Packard
Location:  Manila Philippines
Software Security Auditor
Job Title:  Software Security Auditor
Description:

 The Software Security Auditor is responsible for performing time-sensitive application security assessments against multiple programming languages utilizing a variety of methods including: manual code inspection, configuration review, and automatic static analysis tools. The position requires high-level customer consulting, including teleconferences and occasional onsite presentations; these interactions cover vulnerability report discussion and concept-level remediation advice as the organization’s software security expert.  The candidate must be able to skillfully articulate complex concepts to audiences of different organizational perspectives.  The candidate will have a background in software development in at least one major object-oriented language, will understand OWASP “Top 10” concepts for web application security, SDLC models, and possess a general familiarity with multiple platforms; mobile OS experience is a significant plus.  A level of comfort assessing code logic with multiple, potentially less-familiar languages, is also required.

Desired Skills:

Any of the following development languages

·      Java
·      JavaScript
·      COBOL
·      C#
·      C/C++
·      Objective-C
·      PHP
·      Python
·      Ruby
·      ABAP
·      ColdFusion
·      Various development environments and frameworks a plus (Visual Studio, XCode, VS Razor, Django, Google App Engine, Rails, etc)

Background:

·      Minimum 1 years professional development experience
·      Experience in customer-facing roles - may include: sales, consulting, or account management 
·      System administration familiarity a plus
·      Industry-recognized IT/Security certifications a plus (CISSP, CSSLP, SSCP, GAIC-GWEB (Java and .NET))

**Comment by marksteve** [comment]
Hi @dnesterhp , job posting is now available: http://python.ph/jobs

**Comment by marksteve** [comment]
Clarification: Posting is now enabled. You can post your job and we'll approve it so it shows in the listing.
