### ISSUE TITLE
Python developer

### ISSUE THREAD

**Issue by psc** [pythonph/jobs#18]
**Company Name:** APPone Corp.

**Profile:** We develop large ERP Systems for the Apparel Industrie. A subsidiary of the german SACO Software and Consulting GmbH, over 20 years experience in software development.

**Homepage:**  http://www.appone.eu

**Job Title:** Python developer

**Description:**
You like to be the "man (or women)  in the middle" between the database and frontend?
Do you want to be the wizard behind the scenes ? 
You like:
- Databases ?
- Python ?
- a long term job ?
- a nice work environment (gym, pool) ?

You should send us your CV with your salary requirements to: jobs@appone.eu

**Location:** Manila (Malate)

**Application URL** jobs@appone.eu

**Tags:** python database

**Comment by marksteve** [comment]
@psc Hi Peter! I'm just going to do some changes to jobs before putting this in. Thanks!

**Comment by marksteve** [comment]
Hi @psc, job posting is now available: http://python.ph/jobs

**Comment by marksteve** [comment]
Clarification: Posting is now enabled. You can post your job and we'll approve it so it shows in the listing.
