### ISSUE TITLE
Previous and Next are still showing when only one page exists

### ISSUE THREAD

**Issue by clrke** [pythonph/jobs#2]
Although they are disabled, they should not be there.
![pyjobs](https://cloud.githubusercontent.com/assets/7193634/5986730/33e2db00-a942-11e4-874a-781c420359bf.png)

**Comment by marksteve** [comment]
@arkeidolon Want to take on it? I can help you through setting up React

**Comment by clrke** [comment]
Sure! I'll also add a search feature if you want

**Comment by clrke** [comment]
@marksteve Will there come a time when a job will no longer be available anymore? Should we add a soft delete for that?

**Comment by marksteve** [comment]
@arkeidolon Will post that as a separate issue

See #8

**Comment by clrke** [comment]
Submitted a pull request: 0ed77bb9c48c6b7be24f5d638aa1991413b5d939

**Comment by clrke** [comment]
Closed: https://github.com/pythonph/jobs/pull/9
