### ISSUE TITLE
Full Stack Developer

### ISSUE THREAD

**Issue by kwiltshire** [pythonph/jobs#20]
Company Name: ZipMatch

Profile: We're an online real estate marketplace based right here in the Philippines. We closed our Series A funding a few months ago, and we're growing like crazy! http://techcrunch.com/2015/03/24/zipmatch/

Homepage: www.zipmatch.com

Job Title: Full Stack Software Engineer (Senior Python Experience)

Description: We are looking for an energetic and motivated professional to join the Zipmatch.com Software Engineering team as a Full stack developer. Our Senior Software Engineers work with other members of the IT team to to design, code and ship exciting new features + services to our rapidly growing customer base. They also serve as mentors to junior staff, and guide key technology decisions.

We're especially interested in somebody with a few years python experience to help lead a buildout of integration services. Our architecture is growing up, and we need Python to scale!

Location: BGC, Taguig, Metro Manila

Application URL (Where you want applicants to go): mail careers@zipmatch.com

Tags: Full Stack, Python, AWS, Celery, LAMP, ZipMatch, Startup

**Comment by marksteve** [comment]
Hi @kwiltshire, job posting is now available: http://python.ph/jobs

**Comment by kwiltshire** [comment]
Hi, I don’t see any posting?

**Comment by marksteve** [comment]
@kwiltshire I mean you can register and post jobs now. Register then go to http://python.ph/jobs/post
