### ISSUE TITLE
Add posting date

### ISSUE THREAD

**Issue by titopao** [pythonph/jobs#26]
Probably related to #8, but on a different bent. The model includes fields for creation date, but it is (currently) not displayed on the website itself. The consequence is that there's no way to figure out which posts are new.

Case in point: some of the posts that were removed recently from the PythonPH FB group are displayed but, for some reason, shows up in the middle-to-bottom portion of Page 1. (Which also makes me wonder, what's the default sorting order for the job posts?)

**Comment by titopao** [comment]
^forked this one, let me see if I can do a PR on the template later.

**Comment by zorexsalvo** [comment]
We'll be moving the jobs app to a new repository.
